### ISSUE TITLE
download_data.py unable to download data

### ISSUE THREAD

**Issue by viveknallur** [ramp-kits/supernovae#2]
Running `python download_data.py` doesn't actually download any data. The script assumes that whatever `urlretrieve` retrieves is the actual data.  However, what it actually gets is a 403  error --- You don't have permission to access /supernovae/des_train.pkl on this server

**Comment by aboucaud** [comment]
Hi,

Might have been a server issue when you tried, but the download works fine. 

Can you try again, please ?

**Comment by viveknallur** [comment]
Tried again. It works now. Thanks!

Suggestion: In case that the file names already exist, the script exits silently. Might be worth adding a message saying "files already found and therefore not downloading" or similar. In my case, since the previous 403 error had created the pkl files [albeit with just the error message inside], the script was just silently exiting.

Not extremely important, I realize :-)
